### ISSUE TITLE
프로젝트 개선하기

### ISSUE THREAD

**Issue by imdaxsz** [imdaxsz/bb-front-end#1]
## TODO

- [x] ESLint, prettier 적용하기
- [x] github action 적용하기
- [x] axios interceptor 설정
- [x] 이미지 배경 추가
- [x] 도서 목록 조회 시 최상단 이동 아이콘 추가
- [x] lighthouse 검사 결과를 기반으로 웹 성능 개선
- [x] 검색어 길이 제한 추가
- [x] 후기 백업 요청 시 작성한 후기가 없으면 빈 파일 대신 alert 띄우기
- [x] debounce 적용
- [ ] 회원탈퇴 수정
- [ ] 검색 모달에서 검색 시 깜빡임
- [ ] 리팩토링
   - [x] type safety 고려하여 any 타입 제거
   - [x] 개선한 api를 기반으로 요청, 응답 관련 코드 리팩토링
   - [x] 인증 관리 리팩토링
   - [x] 반복되는 코드 제거 및 코드 리팩토링
   - [x] 컴포넌트 내 로직 hook으로 분리
   - [ ] css 리팩토링
